BEGIN;
CREATE SCHEMA IF NOT EXISTS okk_private;
REVOKE ALL ON SCHEMA okk_private FROM PUBLIC, anon, authenticated;
CREATE TABLE IF NOT EXISTS okk_private.admin (id INTEGER PRIMARY KEY CHECK(id=1), username TEXT NOT NULL, password TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS okk_private.sessions (token TEXT PRIMARY KEY, csrf TEXT NOT NULL, expires DOUBLE PRECISION NOT NULL);
CREATE TABLE IF NOT EXISTS okk_private.attempts (key TEXT PRIMARY KEY, count INTEGER NOT NULL, until DOUBLE PRECISION NOT NULL);
CREATE TABLE IF NOT EXISTS okk_private.projects (id TEXT PRIMARY KEY, slug TEXT UNIQUE NOT NULL, draft TEXT NOT NULL, published TEXT, trashed INTEGER NOT NULL DEFAULT 0, position INTEGER NOT NULL, version INTEGER NOT NULL DEFAULT 1, updated TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS okk_private.media (id TEXT PRIMARY KEY, name TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS okk_private.meta (key TEXT PRIMARY KEY);
CREATE TABLE IF NOT EXISTS okk_private.published_media (project_id TEXT NOT NULL REFERENCES okk_private.projects(id) ON DELETE CASCADE, media_id TEXT NOT NULL REFERENCES okk_private.media(id), PRIMARY KEY(project_id,media_id));
CREATE TABLE IF NOT EXISTS okk_private.clients (id TEXT PRIMARY KEY, name TEXT NOT NULL, logo TEXT NOT NULL, visible INTEGER NOT NULL DEFAULT 0, trashed INTEGER NOT NULL DEFAULT 0, position INTEGER NOT NULL, version INTEGER NOT NULL DEFAULT 1);
CREATE INDEX IF NOT EXISTS published_media_lookup ON okk_private.published_media(media_id);
CREATE INDEX IF NOT EXISTS projects_display_order ON okk_private.projects(trashed,position,id);
CREATE INDEX IF NOT EXISTS clients_media ON okk_private.clients(logo,visible,trashed);
REVOKE ALL ON ALL TABLES IN SCHEMA okk_private FROM PUBLIC, anon, authenticated;
ALTER TABLE okk_private.admin ENABLE ROW LEVEL SECURITY;
ALTER TABLE okk_private.sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE okk_private.attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE okk_private.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE okk_private.media ENABLE ROW LEVEL SECURITY;
ALTER TABLE okk_private.meta ENABLE ROW LEVEL SECURITY;
ALTER TABLE okk_private.published_media ENABLE ROW LEVEL SECURITY;
ALTER TABLE okk_private.clients ENABLE ROW LEVEL SECURITY;
COMMIT;
