"""Browser smoke test against the disposable review server on port 3098."""
import base64
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch(channel='chrome', headless=True)
    page = browser.new_page()
    errors = []
    page.on('pageerror', lambda error: errors.append(str(error)))
    page.goto('http://127.0.0.1:3098/admin/')
    page.locator('#login-form [name=username]').fill('test-editor')
    page.locator('#login-form [name=password]').fill('temporary-check-password')
    page.locator('#login-form button').click()
    page.locator('#nav-clients').click()
    page.wait_for_function("document.querySelectorAll('#client-list .row').length === 15")
    page.add_script_tag(path='/tmp/okk-axe.min.js')
    def audit():
        result = page.evaluate("async () => (await axe.run()).violations.map(v => ({id:v.id, nodes:v.nodes.map(n=>n.target)}))")
        assert not result, result
    audit()
    page.locator('#client-new').click()
    assert not page.locator('#client-visible').is_checked()
    page.locator('#client-form [name=name]').fill('Browser client')
    image = base64.b64decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=')
    page.locator('#client-upload').set_input_files({'name': 'logo.png', 'mimeType': 'image/png', 'buffer': image})
    page.locator('#client-logo-preview img').wait_for()
    page.locator('#client-visible').check(force=True)
    page.locator('#client-save').click()
    page.wait_for_function("document.querySelector('#notice').textContent.includes('반영')")
    audit()
    visitor = browser.new_page()
    visitor.goto('http://127.0.0.1:3098/okk/')
    visitor.locator('.logos img[alt="Browser client"]').wait_for()
    assert visitor.locator('.logos img').count() == 16
    page.locator('#client-visible').uncheck(force=True)
    page.locator('#client-save').click()
    page.wait_for_function("document.querySelector('#notice').textContent.includes('비노출')")
    visitor.reload()
    visitor.wait_for_function("document.querySelectorAll('.logos img').length === 15")
    page.locator('#client-back').click()
    row = page.locator('#client-list .row').filter(has_text='Browser client')
    row.locator('[data-client-action=up]').click()
    page.wait_for_function("document.querySelectorAll('#client-list .row')[14].textContent.includes('Browser client')")
    page.on('dialog', lambda dialog: dialog.accept())
    row.locator('[data-client-action=trash]').click()
    page.wait_for_function("document.querySelectorAll('#client-list .row').length === 15")
    page.locator('#client-filter').select_option('trash')
    page.locator('[data-client-action=restore]').click()
    page.wait_for_function("document.querySelectorAll('#client-list .row').length === 0")
    page.locator('#client-filter').select_option('all')
    page.set_viewport_size({'width': 390, 'height': 844})
    audit()
    assert page.evaluate('document.documentElement.scrollWidth <= innerWidth')
    page.locator('#nav-work').click()
    page.locator('#new').click()
    assert page.locator('#editor').is_visible()
    assert not errors, errors
    browser.close()
    print('PASS: Clients CRUD, visibility, order, restore, mobile, accessibility, Work navigation')
